# Generated by Django 5.1.6 on 2026-04-06 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stumart', '0003_product_institution_product_kyc_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gift_items/')),
                ('weight', models.PositiveIntegerField(default=10, help_text='Relative probability weight. Higher = more likely to land.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, help_text='The product added to cart when this item is won. Leave blank for non-product prizes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_items', to='stumart.product')),
            ],
            options={
                'ordering': ['-weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpinResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('won', 'Won'), ('failed', 'Failed')], default='won', max_length=10)),
                ('spun_at', models.DateTimeField(auto_now_add=True)),
                ('item_name', models.CharField(blank=True, max_length=120)),
                ('gift_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spin_results', to='gift.giftitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-spun_at'],
            },
        ),
    ]
