# Generated by Django 5.1.6 on 2026-04-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftitem',
            name='product',
        ),
        migrations.AddField(
            model_name='giftitem',
            name='in_stock',
            field=models.PositiveIntegerField(default=1, help_text='Number of gift units available'),
        ),
        migrations.AddField(
            model_name='giftitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Gifts are always free (compensation for customers)', max_digits=10),
        ),
    ]
