# Generated by Django 5.1.6 on 2026-04-07 20:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0002_remove_giftitem_product_giftitem_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftitem',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
