# Generated by Django 5.1.6 on 2026-03-09 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('stumart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='service_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='stumart.serviceapplication'),
        ),
    ]
