# Generated by Django 5.1.6 on 2025-09-21 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stumart', '0020_alter_product_delivery_day'),
        ('User', '0012_rename_earnings_companyrider_total_earnings_and_more'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('picker_type', models.CharField(choices=[('company_rider', 'Company Rider'), ('regular_picker', 'Regular Picker'), ('student_picker', 'Student Picker')], max_length=20)),
                ('delivery_confirmation_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('customer_confirmation_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_rider_name', models.CharField(blank=True, max_length=150)),
                ('accepted_rider_phone', models.CharField(blank=True, max_length=20)),
                ('pickup_time', models.CharField(blank=True, max_length=100)),
                ('company_rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_opportunities', to='User.companyrider')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_opportunities', to='Stumart.order')),
                ('user_picker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['unique_code'], name='wallet_deli_unique__3d5142_idx'), models.Index(fields=['status', 'expires_at'], name='wallet_deli_status_01bd52_idx')],
            },
        ),
    ]
