# Generated by Django 5.1.6 on 2025-11-29 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_rename_earnings_companyrider_total_earnings_and_more'),
        ('wallet', '0002_deliveryopportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryopportunity',
            name='company_rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_opportunities', to='User.companyrider'),
        ),
    ]
