# Generated by Django 5.1.6 on 2025-12-05 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stumart', '0021_alter_product_options_alter_cart_cart_code_and_more'),
        ('payment', '0003_remove_withdrawalrequest_withdrawal__user_id_2cda81_idx_and_more'),
        ('wallet', '0004_alter_deliveryopportunity_user_picker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactionaccount',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wallettransactionaccount',
            name='transfer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallettransactionaccount',
            name='transfer_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallettransactionaccount',
            name='transfer_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallettransactionaccount',
            name='transfer_initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallettransactionaccount',
            name='transfer_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransactionaccount',
            name='transaction_type',
            field=models.CharField(choices=[('tax', 'Tax Collection'), ('commission', 'Commission Collection'), ('delivery_payment', 'Delivery Payment'), ('vendor_payment', 'Vendor Payment'), ('company_earnings', 'Company Earnings'), ('rider_earnings', 'Rider Earnings'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('transfer_out', 'Automated Transfer')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='wallettransactionaccount',
            index=models.Index(fields=['reference'], name='wallet_wall_referen_16b5f4_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransactionaccount',
            index=models.Index(fields=['transfer_status'], name='wallet_wall_transfe_4dbad8_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransactionaccount',
            index=models.Index(fields=['transaction_type', 'created_at'], name='wallet_wall_transac_1242e5_idx'),
        ),
    ]
