# Generated by Django 5.1.6 on 2026-01-25 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_wallettransactionaccount_reference_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deliveryopportunity',
            new_name='order_deliv_unique__a00546_idx',
            old_name='wallet_deli_unique__3d5142_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryopportunity',
            new_name='order_deliv_status_367c5a_idx',
            old_name='wallet_deli_status_01bd52_idx',
        ),
        migrations.AlterModelTable(
            name='deliveryopportunity',
            table='order_deliveryopportunity',
        ),
    ]
