# Generated by Django 5.1.6 on 2025-04-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'ADMIN'), ('vendor', 'Vendor'), ('picker', 'Picker'), ('student_picker', 'Student Picker')], max_length=20),
        ),
    ]
