# Generated by Django 5.1.6 on 2025-03-29 15:50

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_otp'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfie_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Selfie Image')),
                ('id_type', models.CharField(choices=[('student_id', 'Student ID Card'), ('national_id', 'National ID Card'), ('drivers_license', "Driver's License"), ('voters_card', "Voter's Card"), ('passport', 'International Passport')], max_length=20, verbose_name='ID Type')),
                ('id_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ID Image')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('none', 'None')], default='none', max_length=10, verbose_name='Verification Status')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Verification Date')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Verification',
                'verbose_name_plural': 'KYC Verifications',
                'ordering': ['-submission_date'],
            },
        ),
    ]
