# Generated by Django 5.1.6 on 2026-03-10 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='kycverification',
            name='kyc_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='kycverification',
            name='kyc_user_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_institution_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_state_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_inst_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendor',
            name='vendor_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendor',
            name='vendor_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendor',
            name='vendor_verified_idx',
        ),
    ]
