# Generated by Django 5.1.6 on 2026-03-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_kycverification_kyc_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='residence',
            field=models.CharField(blank=True, choices=[('on_campus', 'On Campus'), ('off_campus', 'Off Campus')], max_length=20, null=True),
        ),
    ]
