# Generated by Django 5.1.6 on 2025-06-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_subscriptionplan_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='id_type',
            field=models.CharField(choices=[('student_id', 'Student ID Card'), ('course_form', 'Student Course Form'), ('national_id', 'National ID Card'), ('drivers_license', "Driver's License"), ('voters_card', "Voter's Card"), ('passport', 'International Passport')], max_length=20, verbose_name='ID Type'),
        ),
    ]
