# Generated by Django 5.1.6 on 2025-06-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_kycverification_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='residence',
            field=models.CharField(choices=[('on_campus', 'On Campus'), ('off_campus', 'Off Campus')], default=' ', max_length=20),
        ),
    ]
