# Generated by Django 5.1.6 on 2025-07-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_user_residence'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['paystack_recipient_code'], name='User_user_paystac_a247be_idx'),
        ),
    ]
