# Generated by Django 5.1.6 on 2025-07-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_user_options_user_paystack_recipient_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='User_user_paystac_a247be_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='paystack_recipient_code',
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['paystack_recipient_code'], name='User_vendor_paystac_c85016_idx'),
        ),
    ]
