# Generated by Django 5.1.6 on 2025-07-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='business_description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
