# Generated by Django 5.1.6 on 2025-09-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_companyrider'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrider',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
