# Generated by Django 5.1.6 on 2025-09-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_companyrider_earnings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyrider',
            old_name='earnings',
            new_name='total_earnings',
        ),
        migrations.AlterField(
            model_name='companyrider',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('busy', 'Busy'), ('offline', 'Offline')], default='active', max_length=20),
        ),
    ]
