# Generated by Django 5.1.6 on 2025-11-29 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_rename_earnings_companyrider_total_earnings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrider',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riders', to='User.company'),
        ),
    ]
