# Generated by Django 5.1.6 on 2025-12-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_alter_companyrider_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='picker',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentpicker',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='picker',
            index=models.Index(fields=['paystack_recipient_code'], name='User_picker_paystac_d3765e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpicker',
            index=models.Index(fields=['paystack_recipient_code'], name='User_studen_paystac_2bbbde_idx'),
        ),
    ]
