# Generated by Django 5.1.6 on 2026-03-09 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stumart', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Each user has exactly one persistent cart', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stumart.cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='picker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='stumart.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.vendor'),
        ),
        migrations.AddField(
            model_name='pickerreview',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picker_reviews', to='stumart.order'),
        ),
        migrations.AddField(
            model_name='pickerreview',
            name='picker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picker_reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickerreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picker_reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stumart.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='stumart.product'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='stumart.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='stumart.product'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='order',
            field=models.ForeignKey(help_text='The order through which this product was purchased', on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='stumart.order'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stumart.product'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='stumart.product'),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_applications', to='user.vendor'),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stumart.order'),
        ),
        migrations.AddField(
            model_name='vendorreview',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_reviews', to='stumart.order'),
        ),
        migrations.AddField(
            model_name='vendorreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorreview',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='user.vendor'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='cart_user_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='order_num_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='order_user_date'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='order_date_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status', '-created_at'], name='order_status_date'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['picker'], name='order_picker_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['referral_code', '-created_at'], name='order_referral_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['vendor_is_nearby', '-created_at'], name='order_nearby_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pickerreview',
            unique_together={('order', 'picker')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor', '-created_at'], name='prod_vendor_date'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='prod_date_desc'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price', '-created_at'], name='prod_price_asc'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-price', '-created_at'], name='prod_price_desc'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['gender', '-created_at'], name='prod_gender_date'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-in_stock', '-created_at'], name='prod_stock_date'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor', 'price'], name='prod_vendor_price'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='prod_name_search'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['promotion_price'], name='prod_promo'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'vendor'], name='order_item_vendor'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['vendor', 'is_packed'], name='order_item_packed'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='order_items_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='cart_item_lookup'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='cart_items_idx'),
        ),
        migrations.AddIndex(
            model_name='productcolor',
            index=models.Index(fields=['product', 'quantity'], name='prod_color_qty'),
        ),
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together={('product', 'color')},
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product'], name='prod_img_product'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', '-created_at'], name='stumart_pro_product_fd7f20_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['reviewer'], name='stumart_pro_reviewe_2e66b2_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['rating'], name='stumart_pro_rating_78f292_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('product', 'reviewer', 'order')},
        ),
        migrations.AddIndex(
            model_name='productsize',
            index=models.Index(fields=['product', 'quantity'], name='prod_size_qty'),
        ),
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together={('product', 'size')},
        ),
        migrations.AlterUniqueTogether(
            name='vendorreview',
            unique_together={('order', 'vendor')},
        ),
    ]
