# Generated by Django 5.1.6 on 2025-04-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stumart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
