# Generated by Django 5.1.6 on 2026-03-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stumart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='institution',
            field=models.CharField(db_index=True, default='', help_text='Denormalized from vendor.institution for fast filtering', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='kyc_approved',
            field=models.BooleanField(db_index=True, default=False, help_text='Denormalized from vendor KYC status — updated on KYC approval'),
        ),
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.CharField(db_index=True, default='', help_text='Denormalized from vendor.state for fast filtering', max_length=50),
        ),
    ]
