# Generated by Django 5.1.6 on 2026-04-06 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0002_remove_giftitem_product_giftitem_in_stock_and_more'),
        ('stumart', '0003_product_institution_product_kyc_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='gift_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='gift.giftitem'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='stumart.product'),
        ),
    ]
