# Generated by Django 5.1.6 on 2025-04-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stumart', '0003_serviceapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
