# Generated by Django 5.1.6 on 2025-04-02 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stumart', '0004_alter_product_image_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
