# Generated by Django 5.1.6 on 2025-04-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stumart', '0005_cartitem_created_at_cartitem_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
