# Generated by Django 5.1.6 on 2025-05-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stumart', '0005_orderitem_packed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='packed',
        ),
        migrations.AddField(
            model_name='order',
            name='packed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
