# Generated by Django 5.1.6 on 2025-04-08 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stumart', '0007_cart_user_order_orderitem_payment_vendortransaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendortransaction',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='vendortransaction',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='vendorwallet',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='VendorTransaction',
        ),
        migrations.DeleteModel(
            name='VendorWallet',
        ),
        migrations.DeleteModel(
            name='WithdrawalRequest',
        ),
    ]
