# Generated by Django 5.1.6 on 2025-05-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stumart', '0008_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keyword',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
