# Generated by Django 5.1.6 on 2025-04-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stumart', '0008_alter_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=models.CharField(default='red', max_length=50),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(default='M', max_length=20),
        ),
    ]
