# Generated by Django 5.1.6 on 2025-06-09 14:50

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stumart', '0010_alter_product_options_product_promotion_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(help_text='Upload video files only (mp4, avi, mov, wmv, flv, webm)', max_length=255, verbose_name='video')),
                ('name', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(help_text='Upload video files only (mp4, avi, mov, wmv, flv, webm)', max_length=255, verbose_name='video')),
                ('name', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
