# Generated by Django 5.1.6 on 2025-06-10 03:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stumart', '0011_addproductvideo_registervideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promotion_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(99999.99)]),
        ),
    ]
