# Generated by Django 5.1.6 on 2025-06-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stumart', '0014_conversation_message_messagereadstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_day',
            field=models.CharField(default=' ', help_text='Estimated delivery time for the product', max_length=50),
        ),
    ]
