# Generated by Django 5.1.6 on 2025-06-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stumart', '0015_product_delivery_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_packed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='packed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
