# Generated by Django 5.1.6 on 2025-09-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stumart', '0016_orderitem_is_packed_orderitem_packed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comapany_picker_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='company_picker',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
