# Generated by Django 5.1.6 on 2025-09-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stumart', '0017_order_comapany_picker_name_order_company_picker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comapany_picker_name',
        ),
        migrations.AddField(
            model_name='order',
            name='company_picker_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
