# Generated by Django 5.1.6 on 2025-09-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stumart', '0018_remove_order_comapany_picker_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
