# Generated by Django 5.1.6 on 2025-09-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stumart', '0019_delete_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_day',
            field=models.CharField(blank=True, default=' ', help_text='Estimated delivery time for the product', max_length=50, null=True),
        ),
    ]
