# Generated by Django 5.1.6 on 2025-11-29 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stumart', '0020_alter_product_delivery_day'),
        ('User', '0012_rename_earnings_companyrider_total_earnings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['cart_code'], name='cart_code_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['-created_at'], name='cart_created_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='cart_item_lookup'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='cart_items_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='order_num_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='order_user_date'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='order_date_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status', '-created_at'], name='order_status_date'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['picker'], name='order_picker_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'vendor'], name='order_item_vendor'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['vendor', 'is_packed'], name='order_item_packed'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='order_items_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor', '-created_at'], name='prod_vendor_date'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='prod_date_desc'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price', '-created_at'], name='prod_price_asc'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-price', '-created_at'], name='prod_price_desc'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['gender', '-created_at'], name='prod_gender_date'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-in_stock', '-created_at'], name='prod_stock_date'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor', 'price'], name='prod_vendor_price'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='prod_name_search'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['promotion_price'], name='prod_promo'),
        ),
        migrations.AddIndex(
            model_name='productcolor',
            index=models.Index(fields=['product', 'quantity'], name='prod_color_qty'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product'], name='prod_img_product'),
        ),
        migrations.AddIndex(
            model_name='productsize',
            index=models.Index(fields=['product', 'quantity'], name='prod_size_qty'),
        ),
    ]
