# Generated by Django 5.1.6 on 2026-02-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stumart', '0021_alter_product_options_alter_cart_cart_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='takeaway',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
