# Generated by Django 5.1.6 on 2026-02-05 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stumart', '0022_order_takeaway'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='takeaway',
        ),
    ]
