# Generated by Django 5.1.6 on 2026-02-11 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stumart', '0024_order_takeaway'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, help_text='Referral code used for this order', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['referral_code', '-created_at'], name='order_referral_idx'),
        ),
    ]
