# Generated by Django 5.1.6 on 2025-09-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Picker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PickerWallet',
        ),
    ]
