# Generated by Django 5.1.6 on 2026-02-11 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('referral_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('total_referrals', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lifetime_referrals', models.PositiveIntegerField(default=0)),
                ('lifetime_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_paid_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_payout_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_payout_date', models.DateTimeField(blank=True, null=True)),
                ('last_reset_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
            },
        ),
        migrations.CreateModel(
            name='PayoutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referral_count', models.PositiveIntegerField()),
                ('payout_date', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_history', to='referral.referral')),
            ],
            options={
                'verbose_name': 'Payout History',
                'verbose_name_plural': 'Payout Histories',
                'ordering': ['-payout_date'],
            },
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referral_code'], name='ref_code_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['email'], name='ref_email_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['-created_at'], name='ref_created_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['-last_payout_date'], name='ref_payout_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payouthistory',
            index=models.Index(fields=['referral', '-payout_date'], name='payout_ref_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payouthistory',
            index=models.Index(fields=['-payout_date'], name='payout_date_idx'),
        ),
    ]
