# Generated by Django 5.1.6 on 2026-03-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referral_count', models.PositiveIntegerField()),
                ('payout_date', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payout History',
                'verbose_name_plural': 'Payout Histories',
                'ordering': ['-payout_date'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('referral_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('total_referrals', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lifetime_referrals', models.PositiveIntegerField(default=0)),
                ('lifetime_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_paid_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_payout_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_payout_date', models.DateTimeField(blank=True, null=True)),
                ('last_reset_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
            },
        ),
    ]
