# Generated by Django 5.1.6 on 2026-03-09 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referral', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payouthistory',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_history', to='referral.referral'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referral_code'], name='ref_code_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['email'], name='ref_email_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['-created_at'], name='ref_created_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['-last_payout_date'], name='ref_payout_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payouthistory',
            index=models.Index(fields=['referral', '-payout_date'], name='payout_ref_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payouthistory',
            index=models.Index(fields=['-payout_date'], name='payout_date_idx'),
        ),
    ]
