# Generated by Django 5.1.6 on 2025-09-21 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stumart', '0019_delete_wallet'),
        ('User', '0012_rename_earnings_companyrider_total_earnings_and_more'),
        ('payment', '0002_bankaccount_withdrawalfee_withdrawallimit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StuMartWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_tax_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_commission_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'StuMart Platform Wallet',
                'verbose_name_plural': 'StuMart Platform Wallets',
            },
        ),
        migrations.CreateModel(
            name='CompanyWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='User.company')),
            ],
        ),
        migrations.CreateModel(
            name='PickerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('picker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='User.picker')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPickerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_picker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='User.studentpicker')),
            ],
        ),
        migrations.CreateModel(
            name='VendorWallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='User.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('tax', 'Tax Collection'), ('commission', 'Commission Collection'), ('delivery_payment', 'Delivery Payment'), ('vendor_payment', 'Vendor Payment'), ('company_earnings', 'Company Earnings'), ('rider_earnings', 'Rider Earnings'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='Stumart.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('withdrawal_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.withdrawalrequest')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('picker_type', models.CharField(choices=[('company_rider', 'Company Rider'), ('regular_picker', 'Regular Picker'), ('student_picker', 'Student Picker')], max_length=20)),
                ('delivery_confirmation_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('customer_confirmation_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_rider_name', models.CharField(blank=True, max_length=150)),
                ('accepted_rider_phone', models.CharField(blank=True, max_length=20)),
                ('pickup_time', models.CharField(blank=True, max_length=100)),
                ('company_rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_opportunities', to='User.companyrider')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_opportunities', to='Stumart.order')),
                ('user_picker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['unique_code'], name='order_deliv_unique__a00546_idx'), models.Index(fields=['status', 'expires_at'], name='order_deliv_status_367c5a_idx')],
            },
        ),
    ]
