# Generated by Django 5.1.6 on 2025-09-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_rename_earnings_companyrider_total_earnings_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyWallets',
            new_name='CompanyWallet',
        ),
    ]
