export const banks = [
  // Commercial Banks
  "Access Bank",
  "Alternative Bank Limited",
  "Citibank",
  "Ecobank",
  "Fidelity Bank",
  "First Bank of Nigeria",
  "First City Monument Bank",
  "Globus Bank",
  "Guaranty Trust Bank",
  "Heritage Bank",
  "Jaiz Bank",
  "Keystone Bank",
  "Lotus Bank",
  "Nova Commercial Bank",
  "Optimus Bank",
  "Parallex Bank",
  "Polaris Bank",
  "Premium Trust Bank",
  "Providus Bank",
  "Signature Bank",
  "Stanbic IBTC Bank",
  "Standard Chartered Bank",
  "Sterling Bank",
  "SunTrust Bank",
  "TAJBank",
  "Titan Trust Bank",
  "Union Bank of Nigeria",
  "United Bank for Africa",
  "Unity Bank",
  "Wema Bank",
  "Zenith Bank",

  // Development Banks
  "Bank of Agriculture",
  "Bank of Industry",
  "Development Bank of Nigeria",
  "Federal Mortgage Bank of Nigeria",
  "Nigerian Export-Import Bank",
  "The Infrastructure Bank",

  // Major Microfinance Banks
  "Accion Microfinance Bank",
  "Advans La Fayette Microfinance Bank",
  "CashX Microfinance Bank",
  "Covenant Microfinance Bank",
  "Dot Microfinance Bank",
  "Empire Trust Microfinance Bank",
  "FairMoney Microfinance Bank",
  "Finca Microfinance Bank",
  "Infinity Microfinance Bank",
  "Kuda Bank",
  "LAPO Microfinance Bank",
  "Mainstreet Microfinance Bank",
  "Mint Finex Microfinance Bank",
  "Mkobo Microfinance Bank",
  "Moniepoint Microfinance Bank",
  "Moneyfield Microfinance Bank",
  "Mutual Trust Microfinance Bank",
  "Opay",
  "Palmpay",
  "Peace Microfinance Bank",
  "Pecan Trust Microfinance Bank",
  "Pryme Microfinance Bank",
  "Raven Bank",
  "Rephidim Microfinance Bank",
  "Rex Microfinance Bank",
  "Rubies Bank",
  "Shepherd Trust Microfinance Bank",
  "Solid Allianze Microfinance Bank",
  "Sparkle Bank",
  "VFD Microfinance Bank",
].sort();
