export const nigeriaStates = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
  "Federal Capital Territory",
].sort();

export const nigeriaInstitutions = {
  Abia: [
    "Abia State Polytechnic, Aba",
    "Abia State University, Uturu",
    "Gregory University, Uturu",
    "Michael Okpara University of Agriculture, Umudike",
    "Rhema University, Obeama-Asa",
    "Temple Gate Polytechnic, Aba",
  ],
  Adamawa: [
    "Adamawa State Polytechnic, Yola",
    "Adamawa State University, Mubi",
    "American University of Nigeria, Yola",
    "Federal Polytechnic, Mubi",
    "Modibbo Adama University of Technology, Yola",
  ],
  Akwa_Ibom: [
    "Akwa Ibom State Polytechnic, Ikot Osurua",
    "Akwa Ibom State University, Ikot Akpaden",
    "Obong University, Obong Ntak",
    "Ritman University, Ikot Ekpene",
    "University of Uyo, Uyo",
  ],
  Anambra: [
    "Anambra State Polytechnic, Mgbakwu",
    "Chukwuemeka Odumegwu Ojukwu University, Uli",
    "Federal Polytechnic, Oko",
    "Madonna University, Okija",
    "Nnamdi Azikiwe University, Awka",
    "Paul University, Awka",
    "Tansian University, Umunya",
  ],
  Bauchi: [
    "Abubakar Tafawa Balewa University, Bauchi",
    "Bauchi State University, Gadau",
    "Federal Polytechnic, Bauchi",
    "Tatari Ali Polytechnic, Bauchi",
  ],
  Bayelsa: [
    "Federal Polytechnic, Ekowe",
    "Federal University, Otuoke",
    "Niger Delta University, Wilberforce Island",
    "University of Africa, Toru-Orua",
  ],
  Benue: [
    "Benue State Polytechnic, Ugbokolo",
    "Benue State University, Makurdi",
    "Federal University of Agriculture, Makurdi",
    "University of Mkar, Mkar",
  ],
  Borno: [
    "Borno State University, Maiduguri",
    "Federal Polytechnic, Mubi",
    "Ramat Polytechnic, Maiduguri",
    "University of Maiduguri, Maiduguri",
  ],
  Cross_River: [
    "Arthur Jarvis University, Calabar",
    "Cross River State University of Science and Technology, Calabar",
    "Cross River University of Technology, Calabar",
    "University of Calabar, Calabar",
  ],
  Delta: [
    "Delta State Polytechnic, Ogwashi-Uku",
    "Delta State Polytechnic, Otefe-Oghara",
    "Delta State Polytechnic, Ozoro",
    "Delta State University, Abraka",
    "Federal University of Petroleum Resources, Effurun",
    "Novena University, Ogume",
    "Western Delta University, Oghara",
  ],
  Ebonyi: [
    "Akanu Ibiam Federal Polytechnic, Unwana",
    "Ebonyi State University, Abakaliki",
    "Federal University, Ndufu-Alike",
  ],
  Edo: [
    "Ambrose Alli University, Ekpoma",
    "Auchi Polytechnic, Auchi",
    "Benson Idahosa University, Benin City",
    "Edo State Polytechnic, Usen",
    "Edo University, Iyamho",
    "Igbinedion University, Okada",
    "University of Benin, Benin City",
    "Wellspring University, Benin City",
  ],
  Ekiti: [
    "Afe Babalola University, Ado-Ekiti",
    "Crown Polytechnic, Ado-Ekiti",
    "Ekiti State University, Ado-Ekiti",
    "Federal Polytechnic, Ado-Ekiti",
    "Federal University, Oye-Ekiti",
  ],
  Enugu: [
    "Coal City University, Enugu",
    "Enugu State Polytechnic, Iwollo",
    "Enugu State University of Science and Technology, Enugu",
    "Federal Polytechnic, Idah",
    "Godfrey Okoye University, Enugu",
    "Institute of Management and Technology, Enugu",
    "Renaissance University, Enugu",
    "University of Nigeria, Nsukka",
  ],
  FCT_Abuja: [
    "African University of Science and Technology, Abuja",
    "Baze University, Abuja",
    "FCT College of Education, Zuba",
    "National Open University of Nigeria, Abuja",
    "Nigerian Law School, Bwari",
    "Nile University of Nigeria, Abuja",
    "University of Abuja, Abuja",
    "Veritas University, Abuja",
  ],
  Gombe: [
    "Federal University, Kashere",
    "Gombe State University, Gombe",
    "Gombe State University of Science and Technology, Kumo",
  ],
  Imo: [
    "Alvan Ikoku Federal College of Education, Owerri",
    "Eastern Palm University, Ogboko",
    "Federal Polytechnic, Nekede",
    "Federal University of Technology, Owerri",
    "Imo State Polytechnic, Umuagwo",
    "Imo State University, Owerri",
  ],
  Jigawa: [
    "Federal University, Dutse",
    "Jigawa State Polytechnic, Dutse",
    "Sule Lamido University, Kafin Hausa",
  ],
  Kaduna: [
    "Ahmadu Bello University, Zaria",
    "Air Force Institute of Technology, Kaduna",
    "Greenfield University, Kaduna",
    "Kaduna Polytechnic, Kaduna",
    "Kaduna State University, Kaduna",
    "Nigerian College of Aviation Technology, Zaria",
    "Nigerian Defence Academy, Kaduna",
    "Nuhu Bamalli Polytechnic, Zaria",
  ],
  Kano: [
    "Bayero University, Kano",
    "Federal College of Education, Kano",
    "Kano State Polytechnic, Kano",
    "Kano University of Science and Technology, Wudil",
    "Maitama Sule University, Kano",
    "Skyline University Nigeria, Kano",
    "Yusuf Maitama Sule University, Kano",
  ],
  Katsina: [
    "Al-Qalam University, Katsina",
    "Federal College of Education, Katsina",
    "Federal University, Dutsin-Ma",
    "Hassan Usman Katsina Polytechnic, Katsina",
    "Umaru Musa Yar'adua University, Katsina",
  ],
  Kebbi: [
    "Federal University, Birnin Kebbi",
    "Kebbi State Polytechnic, Dakingari",
    "Kebbi State University of Science and Technology, Aliero",
    "Waziri Umaru Federal Polytechnic, Birnin Kebbi",
  ],
  Kogi: [
    "Federal University, Lokoja",
    "Kogi State Polytechnic, Lokoja",
    "Kogi State University, Anyigba",
    "Salem University, Lokoja",
  ],
  Kwara: [
    "Ahman Pategi University, Patigi",
    "Al-Hikmah University, Ilorin",
    "Federal Polytechnic, Offa",
    "Kwara State Polytechnic, Ilorin",
    "Kwara State University, Malete",
    "Landmark University, Omu-Aran",
    "Summit University, Offa",
    "University of Ilorin, Ilorin",
  ],
  Lagos: [
    "Anchor University, Lagos",
    "Caleb University, Imota",
    "Federal College of Education (Technical), Akoka",
    "Federal College of Fisheries and Marine Technology, Lagos",
    "Lagos Business School, Lagos",
    "Lagos State Polytechnic, Ikorodu",
    "Lagos State University, Ojo",
    "Nigerian Institute of Journalism, Lagos",
    "Pan-Atlantic University, Lagos",
    "University of Lagos, Akoka",
    "Yaba College of Technology, Lagos",
  ],
  Nasarawa: [
    "Bingham University, Karu",
    "Federal Polytechnic, Nasarawa",
    "Federal University, Lafia",
    "Nasarawa State Polytechnic, Lafia",
    "Nasarawa State University, Keffi",
  ],
  Niger: [
    "Federal Polytechnic, Bida",
    "Federal University of Technology, Minna",
    "Ibrahim Badamasi Babangida University, Lapai",
    "Niger State Polytechnic, Zungeru",
  ],
  Ogun: [
    "Abraham Adesanya Polytechnic, Ijebu-Igbo",
    "Babcock University, Ilishan-Remo",
    "Bells University of Technology, Ota",
    "Covenant University, Ota",
    "Crawford University, Igbesa",
    "Federal Polytechnic, Ilaro",
    "Federal University of Agriculture, Abeokuta",
    "Moshood Abiola Polytechnic, Abeokuta",
    "Mountain Top University, Makogi Oba",
    "Olabisi Onabanjo University, Ago-Iwoye",
    "Tai Solarin University of Education, Ijagun",
  ],
  Ondo: [
    "Achievers University, Owo",
    "Adeyemi College of Education, Ondo",
    "Adekunle Ajasin University, Akungba-Akoko",
    "Federal University of Technology, Akure",
    "Olusegun Agagu University of Science and Technology, Okitipupa",
    "Rufus Giwa Polytechnic, Owo",
    "University of Medical Sciences, Ondo",
  ],
  Osun: [
    "Adeleke University, Ede",
    "Bowen University, Iwo",
    "Fountain University, Osogbo",
    "Joseph Ayo Babalola University, Ikeji-Arakeji",
    "Obafemi Awolowo University, Ile-Ife",
    "Osun State College of Technology, Esa Oke",
    "Osun State Polytechnic, Iree",
    "Osun State University, Osogbo",
    "The Polytechnic, Ile-Ife",
  ],
  Oyo: [
    "Ajayi Crowther University, Oyo",
    "Dominican University, Ibadan",
    "Federal College of Animal Health and Production Technology, Ibadan",
    "Federal College of Forestry, Ibadan",
    "Ladoke Akintola University of Technology, Ogbomoso",
    "Lead City University, Ibadan",
    "National Open University of Nigeria, Ibadan Study Centre",
    "The Polytechnic, Ibadan",
    "The Technical University, Ibadan",
    "University of Ibadan, Ibadan",
  ],
  Plateau: [
    "Federal College of Education, Pankshin",
    "Federal College of Forestry, Jos",
    "Federal School of Medical Laboratory Technology, Jos",
    "Plateau State Polytechnic, Barkin Ladi",
    "Plateau State University, Bokkos",
    "University of Jos, Jos",
  ],
  Rivers: [
    "Captain Elechi Amadi Polytechnic, Port Harcourt",
    "Ignatius Ajuru University of Education, Port Harcourt",
    "Ken Saro-Wiwa Polytechnic, Bori",
    "Madonna University, Elele Campus",
    "Rivers State University, Port Harcourt",
    "University of Port Harcourt, Port Harcourt",
  ],
  Sokoto: [
    "Shehu Shagari College of Education, Sokoto",
    "Sokoto State University, Sokoto",
    "Usmanu Danfodiyo University, Sokoto",
  ],
  Taraba: [
    "Federal University, Wukari",
    "Kwararafa University, Wukari",
    "Taraba State Polytechnic, Suntai",
    "Taraba State University, Jalingo",
  ],
  Yobe: [
    "Federal Polytechnic, Damaturu",
    "Federal University, Gashua",
    "Yobe State University, Damaturu",
  ],
  Zamfara: [
    "Federal Polytechnic, Kaura Namoda",
    "Federal University, Gusau",
    "Zamfara State University, Talata Mafara",
  ],
};

export const businessCategories = [
  "Food",
  "Fashion",
  "Technology",
  "Accessories",
  "Home",
  "Books",
  "Electronics",
  "Others",
];

export const otherBusinessCategories = [
  { value: "laundry", label: "Laundry Services" },
  { value: "note_writing", label: "Note Writing" },
  { value: "assignment_help", label: "Assignment Help" },
  { value: "barbing", label: "Barbing Services" },
  { value: "hair_styling", label: "Hair Styling" },
  { value: "printing", label: "Printing Services" },
  { value: "computer_repairs", label: "Computer Repairs" },
  { value: "phone_repairs", label: "Phone Repairs" },
  { value: "tutoring", label: "Tutoring" },
  { value: "photography", label: "Photography" },
  { value: "graphic_design", label: "Graphic Design" },
  { value: "tailoring", label: "Tailoring" },
  { value: "cleaning", label: "Cleaning Services" },
  { value: "event_planning", label: "Event Planning" },
];

export const userTypes = ["Student", "Picker", "Vendor", "Student Picker"];

export const fleetTypes = ["Bike", "Bicycle"];
