# Generated by Django 5.1.6 on 2026-03-09 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookmark', '0001_initial'),
        ('stumart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='product',
            field=models.ForeignKey(help_text='The bookmarked product', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='stumart.product'),
        ),
    ]
