# Generated by Django 5.1.6 on 2026-03-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='updated_at',
        ),
    ]
