# Generated by Django 5.1.6 on 2026-03-09 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0004_remove_bookmark_updated_at'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='The user who saved the vendor', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(help_text='The bookmarked vendor', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='user.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='vbookmark_user_date'), models.Index(fields=['user', 'vendor'], name='vbookmark_user_vendor')],
                'unique_together': {('user', 'vendor')},
            },
        ),
    ]
