# Generated by Django 5.1.6 on 2026-03-09 08:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(max_length=10)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=100)),
                ('paystack_recipient_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_bank_accounts',
                'ordering': ['-is_default', '-last_used', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('vendor', 'Vendor'), ('picker', 'Picker'), ('student_picker', 'Student Picker'), ('company', 'Company'), ('all', 'All Users')], default='all', max_length=20)),
                ('fee_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('tiered', 'Tiered')], default='percentage', max_length=20)),
                ('percentage_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage fee (e.g., 1.5 for 1.5%)', max_digits=5)),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed fee amount', max_digits=10)),
                ('minimum_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum fee amount', max_digits=10)),
                ('maximum_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum fee amount (0 for no limit)', max_digits=10)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum withdrawal amount for this fee', max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum withdrawal amount for this fee (0 for no limit)', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'withdrawal_fees',
                'ordering': ['user_type', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('vendor', 'Vendor'), ('picker', 'Picker'), ('student_picker', 'Student Picker'), ('company', 'Company'), ('all', 'All Users')], default='all', max_length=20)),
                ('limit_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('per_transaction', 'Per Transaction')], max_length=20)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'withdrawal_limits',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('vendor', 'Vendor'), ('picker', 'Picker'), ('student_picker', 'Student Picker'), ('company', 'Company')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=10, null=True)),
                ('account_number', models.CharField(blank=True, max_length=10, null=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('paystack_recipient_code', models.CharField(blank=True, max_length=100, null=True)),
                ('paystack_transfer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('is_automated', models.BooleanField(default=False, help_text='True if this withdrawal was triggered automatically after order completion')),
                ('automation_triggered_at', models.DateTimeField(blank=True, help_text='When the automated withdrawal was triggered', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the withdrawal', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
