# Generated by Django 5.1.6 on 2026-03-09 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('stumart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_bank_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='withdrawallimit',
            unique_together={('user_type', 'limit_type')},
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='related_order',
            field=models.ForeignKey(blank=True, help_text='The order that triggered this automated withdrawal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automated_withdrawals', to='stumart.order'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('user', 'account_number', 'bank_code')},
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['user', 'status'], name='payment_wit_user_id_a02d11_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['paystack_reference'], name='payment_wit_paystac_12cf44_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['is_automated', 'created_at'], name='payment_wit_is_auto_be61be_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['related_order'], name='payment_wit_related_8285c7_idx'),
        ),
    ]
