# Generated by Django 5.1.6 on 2025-09-21 07:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(max_length=10)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=100)),
                ('paystack_recipient_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_bank_accounts',
                'ordering': ['-is_default', '-last_used', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('vendor', 'Vendor'), ('picker', 'Picker'), ('student_picker', 'Student Picker'), ('company', 'Company'), ('all', 'All Users')], default='all', max_length=20)),
                ('fee_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('tiered', 'Tiered')], default='percentage', max_length=20)),
                ('percentage_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage fee (e.g., 1.5 for 1.5%)', max_digits=5)),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed fee amount', max_digits=10)),
                ('minimum_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum fee amount', max_digits=10)),
                ('maximum_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum fee amount (0 for no limit)', max_digits=10)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum withdrawal amount for this fee', max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum withdrawal amount for this fee (0 for no limit)', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'withdrawal_fees',
                'ordering': ['user_type', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('vendor', 'Vendor'), ('picker', 'Picker'), ('student_picker', 'Student Picker'), ('company', 'Company'), ('all', 'All Users')], default='all', max_length=20)),
                ('limit_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('per_transaction', 'Per Transaction')], max_length=20)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'withdrawal_limits',
            },
        ),
        migrations.RemoveIndex(
            model_name='withdrawalrequest',
            name='payment_wit_user_id_a02d11_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawalrequest',
            new_name='withdrawal__paystac_c8c3d8_idx',
            old_name='payment_wit_paystac_12cf44_idx',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='transfer_fee',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes', null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Requested withdrawal amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, help_text='Final amount after fees', max_digits=12),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['user', '-created_at'], name='withdrawal__user_id_2cda81_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status', '-created_at'], name='withdrawal__status_e67567_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['created_at'], name='withdrawal__created_f612ba_idx'),
        ),
        migrations.AlterModelTable(
            name='withdrawalrequest',
            table='withdrawal_requests',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_bank_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='withdrawallimit',
            unique_together={('user_type', 'limit_type')},
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('user', 'account_number', 'bank_code')},
        ),
    ]
