# Generated by Django 5.1.6 on 2025-11-29 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stumart', '0021_alter_product_options_alter_cart_cart_code_and_more'),
        ('payment', '0002_bankaccount_withdrawalfee_withdrawallimit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='withdrawalrequest',
            name='withdrawal__user_id_2cda81_idx',
        ),
        migrations.RemoveIndex(
            model_name='withdrawalrequest',
            name='withdrawal__status_e67567_idx',
        ),
        migrations.RemoveIndex(
            model_name='withdrawalrequest',
            name='withdrawal__created_f612ba_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawalrequest',
            new_name='payment_wit_paystac_12cf44_idx',
            old_name='withdrawal__paystac_c8c3d8_idx',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='automation_triggered_at',
            field=models.DateTimeField(blank=True, help_text='When the automated withdrawal was triggered', null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='is_automated',
            field=models.BooleanField(default=False, help_text='True if this withdrawal was triggered automatically after order completion'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='related_order',
            field=models.ForeignKey(blank=True, help_text='The order that triggered this automated withdrawal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automated_withdrawals', to='Stumart.order'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='account_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the withdrawal', null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['user', 'status'], name='payment_wit_user_id_a02d11_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['is_automated', 'created_at'], name='payment_wit_is_auto_be61be_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['related_order'], name='payment_wit_related_8285c7_idx'),
        ),
        migrations.AlterModelTable(
            name='withdrawalrequest',
            table=None,
        ),
    ]
